

set_property PACKAGE_PIN AA19 [get_ports hsync]
set_property PACKAGE_PIN Y19 [get_ports vsync]
set_property IOSTANDARD LVCMOS18 [get_ports hsync]
set_property IOSTANDARD LVCMOS18 [get_ports vsync]
set_property PACKAGE_PIN V18 [get_ports {vga_output[11]}]
set_property PACKAGE_PIN V19 [get_ports {vga_output[10]}]
set_property PACKAGE_PIN U20 [get_ports {vga_output[9]}]
set_property PACKAGE_PIN V20 [get_ports {vga_output[8]}]
set_property PACKAGE_PIN AA21 [get_ports {vga_output[7]}]
set_property PACKAGE_PIN AB21 [get_ports {vga_output[6]}]
set_property PACKAGE_PIN AA22 [get_ports {vga_output[5]}]
set_property PACKAGE_PIN AB22 [get_ports {vga_output[4]}]
set_property PACKAGE_PIN AB19 [get_ports {vga_output[3]}]
set_property PACKAGE_PIN AB20 [get_ports {vga_output[2]}]
set_property PACKAGE_PIN Y20 [get_ports {vga_output[1]}]
set_property PACKAGE_PIN Y21 [get_ports {vga_output[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {vga_output[2]}]

#set_property PACKAGE_PIN U14 [get_ports led]
#set_property IOSTANDARD LVCMOS18 [get_ports led]

set_property PACKAGE_PIN U19 [get_ports processing_done]
set_property PACKAGE_PIN F22 [get_ports rst]
set_property PACKAGE_PIN M15 [get_ports select_input]
set_property PACKAGE_PIN U14 [get_ports done_output]
set_property IOSTANDARD LVCMOS18 [get_ports processing_done]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports select_input]
set_property IOSTANDARD LVCMOS18 [get_ports done_output]
